package me.huding.luobo.model;

import me.huding.luobo.model.base.BaseAdminUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminUser extends BaseAdminUser<AdminUser> {
	public static final AdminUser dao = new AdminUser();
}
