package me.huding.luobo.model;

import me.huding.luobo.model.base.BaseAnnouncement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Announcement extends BaseAnnouncement<Announcement> {
	public static final Announcement dao = new Announcement();
}
