package me.huding.luobo.model;

import me.huding.luobo.model.base.BaseAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attachment extends BaseAttachment<Attachment> {
	public static final Attachment dao = new Attachment();
}
