package me.huding.luobo.model;

import me.huding.luobo.model.base.BaseMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Message extends BaseMessage<Message> {
	public static final Message dao = new Message();
}
