package me.huding.luobo.model;


import java.util.List;

import com.jfinal.plugin.activerecord.TableMapping;

import me.huding.luobo.model.base.BaseTags;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tags extends BaseTags<Tags> {
	public static final Tags dao = new Tags();
	
	
	public static List<Tags> findAll(){
		String tableName = TableMapping.me().getTable(Tags.class).getName();
		String sql = "select * from " + tableName;
		return dao.find(sql);
	}
}
