package me.huding.luobo.model;

import me.huding.luobo.model.base.BaseTimeline;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Timeline extends BaseTimeline<Timeline> {
	public static final Timeline dao = new Timeline();
}
