package me.huding.luobo.model;

import me.huding.luobo.model.base.BaseTrackLogin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TrackLogin extends BaseTrackLogin<TrackLogin> {
	public static final TrackLogin dao = new TrackLogin();
}
