package me.huding.luobo.model;

import me.huding.luobo.model.base.BaseType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Type extends BaseType<Type> {
	public static final Type dao = new Type();
}
