package me.huding.luobo.model;

import me.huding.luobo.model.base.BaseUserPermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserPermission extends BaseUserPermission<UserPermission> {
	public static final UserPermission dao = new UserPermission();
}
