package me.huding.luobo.model;

import me.huding.luobo.model.base.BaseUserRegister;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRegister extends BaseUserRegister<UserRegister> {
	public static final UserRegister dao = new UserRegister();
}
