package me.huding.luobo.model;

import java.util.List;

import com.jfinal.plugin.activerecord.TableMapping;

import me.huding.luobo.model.base.BaseCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	public static final Category dao = new Category();
	
	public static List<Category> findAll(){
		String tableName = TableMapping.me().getTable(Category.class).getName();
		String sql = "select * from " + tableName;
		return dao.find(sql);
	}
}
