package me.huding.luobo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserPermission<M extends BaseUserPermission<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPermission(java.lang.Integer permission) {
		set("permission", permission);
	}

	public java.lang.Integer getPermission() {
		return get("permission");
	}

	public void setPermissionName(java.lang.String permissionName) {
		set("permission_name", permissionName);
	}

	public java.lang.String getPermissionName() {
		return get("permission_name");
	}

}
