package me.huding.luobo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setReceiver(java.lang.Integer receiver) {
		set("receiver", receiver);
	}

	public java.lang.Integer getReceiver() {
		return get("receiver");
	}

	public void setSender(java.lang.Integer sender) {
		set("sender", sender);
	}

	public java.lang.Integer getSender() {
		return get("sender");
	}

	public void setSenderName(java.lang.String senderName) {
		set("sender_name", senderName);
	}

	public java.lang.String getSenderName() {
		return get("sender_name");
	}

	public void setSendTime(java.util.Date sendTime) {
		set("send_time", sendTime);
	}

	public java.util.Date getSendTime() {
		return get("send_time");
	}

	public void setIsRead(java.lang.Boolean isRead) {
		set("is_read", isRead);
	}

	public java.lang.Boolean getIsRead() {
		return get("is_read");
	}

	public void setReadTime(java.util.Date readTime) {
		set("read_time", readTime);
	}

	public java.util.Date getReadTime() {
		return get("read_time");
	}

}
