package me.huding.luobo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotice<M extends BaseNotice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setStart(java.util.Date start) {
		set("start", start);
	}

	public java.util.Date getStart() {
		return get("start");
	}

	public void setEnd(java.util.Date end) {
		set("end", end);
	}

	public java.util.Date getEnd() {
		return get("end");
	}

	public void setVisible(java.lang.Boolean visible) {
		set("visible", visible);
	}

	public java.lang.Boolean getVisible() {
		return get("visible");
	}

}
