package me.huding.luobo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setSequence(java.lang.Integer sequence) {
		set("sequence", sequence);
	}

	public java.lang.Integer getSequence() {
		return get("sequence");
	}

	public void setSerialNumber(java.lang.String serialNumber) {
		set("serialNumber", serialNumber);
	}

	public java.lang.String getSerialNumber() {
		return get("serialNumber");
	}

	public void setStudentId(java.lang.String studentId) {
		set("student_id", studentId);
	}

	public java.lang.String getStudentId() {
		return get("student_id");
	}

	public void setUniversityId(java.lang.String universityId) {
		set("university_id", universityId);
	}

	public java.lang.String getUniversityId() {
		return get("university_id");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return get("openid");
	}

	public void setNick(java.lang.String nick) {
		set("nick", nick);
	}

	public java.lang.String getNick() {
		return get("nick");
	}

	public void setHeadurl(java.lang.String headurl) {
		set("headurl", headurl);
	}

	public java.lang.String getHeadurl() {
		return get("headurl");
	}

	public void setBind(java.lang.Integer bind) {
		set("bind", bind);
	}

	public java.lang.Integer getBind() {
		return get("bind");
	}

	public void setBdpushid(java.lang.String bdpushid) {
		set("bdpushid", bdpushid);
	}

	public java.lang.String getBdpushid() {
		return get("bdpushid");
	}

	public void setBdchannelid(java.lang.String bdchannelid) {
		set("bdchannelid", bdchannelid);
	}

	public java.lang.String getBdchannelid() {
		return get("bdchannelid");
	}

	public void setVersion(java.lang.String version) {
		set("version", version);
	}

	public java.lang.String getVersion() {
		return get("version");
	}

}
