package me.huding.luobo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAttachment<M extends BaseAttachment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setOldName(java.lang.String oldName) {
		set("old_name", oldName);
	}

	public java.lang.String getOldName() {
		return get("old_name");
	}

	public void setNewName(java.lang.String newName) {
		set("new_name", newName);
	}

	public java.lang.String getNewName() {
		return get("new_name");
	}

	public void setExtName(java.lang.String extName) {
		set("ext_name", extName);
	}

	public java.lang.String getExtName() {
		return get("ext_name");
	}

	public void setMimeType(java.lang.String mimeType) {
		set("mime_type", mimeType);
	}

	public java.lang.String getMimeType() {
		return get("mime_type");
	}

	public void setSize(java.lang.Integer size) {
		set("size", size);
	}

	public java.lang.Integer getSize() {
		return get("size");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setCreationTime(java.util.Date creationTime) {
		set("creation_time", creationTime);
	}

	public java.util.Date getCreationTime() {
		return get("creation_time");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setRefId(java.lang.Integer refId) {
		set("ref_id", refId);
	}

	public java.lang.Integer getRefId() {
		return get("ref_id");
	}

}
