package me.huding.luobo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTrackLogin<M extends BaseTrackLogin<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setLoginUserId(java.lang.Long loginUserId) {
		set("login_user_id", loginUserId);
	}

	public java.lang.Long getLoginUserId() {
		return get("login_user_id");
	}

	public void setLoginDate(java.util.Date loginDate) {
		set("login_date", loginDate);
	}

	public java.util.Date getLoginDate() {
		return get("login_date");
	}

	public void setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
	}

	public java.lang.String getLoginIp() {
		return get("login_ip");
	}

	public void setLogoutDate(java.util.Date logoutDate) {
		set("logout_date", logoutDate);
	}

	public java.util.Date getLogoutDate() {
		return get("logout_date");
	}

	public void setSessionId(java.lang.String sessionId) {
		set("session_id", sessionId);
	}

	public java.lang.String getSessionId() {
		return get("session_id");
	}

	public void setBrowser(java.lang.String browser) {
		set("browser", browser);
	}

	public java.lang.String getBrowser() {
		return get("browser");
	}

	public void setUserAgent(java.lang.String userAgent) {
		set("user_agent", userAgent);
	}

	public java.lang.String getUserAgent() {
		return get("user_agent");
	}

}
