package me.huding.luobo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRegister<M extends BaseUserRegister<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setRegStatus(java.lang.Integer regStatus) {
		set("reg_status", regStatus);
	}

	public java.lang.Integer getRegStatus() {
		return get("reg_status");
	}

	public void setRefUserId(java.lang.String refUserId) {
		set("ref_user_id", refUserId);
	}

	public java.lang.String getRefUserId() {
		return get("ref_user_id");
	}

	public void setFirstname(java.lang.String firstname) {
		set("firstname", firstname);
	}

	public java.lang.String getFirstname() {
		return get("firstname");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setSex(java.lang.Boolean sex) {
		set("sex", sex);
	}

	public java.lang.Boolean getSex() {
		return get("sex");
	}

	public void setRegDate(java.util.Date regDate) {
		set("reg_date", regDate);
	}

	public java.util.Date getRegDate() {
		return get("reg_date");
	}

	public void setRegIp(java.lang.String regIp) {
		set("reg_ip", regIp);
	}

	public java.lang.String getRegIp() {
		return get("reg_ip");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

}
