package me.huding.luobo.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setCdate(java.util.Date cdate) {
		set("cdate", cdate);
	}

	public java.util.Date getCdate() {
		return get("cdate");
	}

	public void setLikeNum(java.lang.Integer likeNum) {
		set("likeNum", likeNum);
	}

	public java.lang.Integer getLikeNum() {
		return get("likeNum");
	}

	public void setHateNum(java.lang.Integer hateNum) {
		set("hateNum", hateNum);
	}

	public java.lang.Integer getHateNum() {
		return get("hateNum");
	}

	public void setParent(java.lang.String parent) {
		set("parent", parent);
	}

	public java.lang.String getParent() {
		return get("parent");
	}

	public void setBlogID(java.lang.String blogID) {
		set("blogID", blogID);
	}

	public java.lang.String getBlogID() {
		return get("blogID");
	}

	public void setShareNum(java.lang.Integer shareNum) {
		set("shareNum", shareNum);
	}

	public java.lang.Integer getShareNum() {
		return get("shareNum");
	}

	public void setReplyNum(java.lang.Integer replyNum) {
		set("replyNum", replyNum);
	}

	public java.lang.Integer getReplyNum() {
		return get("replyNum");
	}

	public void setHeadURL(java.lang.String headURL) {
		set("headURL", headURL);
	}

	public java.lang.String getHeadURL() {
		return get("headURL");
	}

	public void setCheck(java.lang.Integer check) {
		set("check", check);
	}

	public java.lang.Integer getCheck() {
		return get("check");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
